#!/usr/bin/env bash

CELERY_PID=/var/run/alterspace/celery.pid
FLASK_PID=/var/run/alterspace/flask.pid

function start_all {
  local ALTERSPACE_DIR
  ALTERSPACE_DIR="$(dirname "$0")/../"
  cd "${ALTERSPACE_DIR}"
  FLASK_APP=run.py FLASK_DEBUG=1 python -m flask run -p 5000 &
  celery -A backend.tasks worker --pidfile /var/run/alterspace/celery.pid &
}

function halt_job {
    job="${1}"
    pid="$(cat "${2}")"
    echo "Performing graceful exit of ${job}..."
    kill -15 "${pid}"
    sleep 5
    pgrep --pidfile "${2}" && echo "${job} still running. Attempting to force-kill. Doublecheck manually" && kill -9 "${pid}"
}

function nuke_python {
    killall python
}

function stop_all {
    halt_job "celery" "${CELERY_PID}" &
    # halt_job "flask" "${FLASK_PID}" &
    nuke_python &
}

case "$1" in
  start) start_all ;;
  stop) stop_all ;;
  *)
    echo "Control the alterspace processes"
    echo ""
    echo "Usage:"
    echo " ./runner [start|stop]"
    echo ""
    echo "Options:"
    echo " start     start celery and flask jobs"
    echo " stop      stop celery and flask jobs"
    echo ""
    echo "For more details, see https://github.com/harvard-lil/alter-space"
  ;;
esac
