/* eslint-disable */
require('./abstract')
require('./breathe')
require('./home')
require('./info')
require('./mute')
require('./nature')
require('./pause')
require('./play')
require('./urban')
require('./volume')
